services:
  mongodb:
    image: docker.io/library/mongo:latest
    container_name: local-mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    volumes:
      - mongo-data:/data/db:Z # ':Z' is essential for SELinux systems

volumes:
  mongo-data:
